version: '3'
services:
  redis:
    container_name: misp-redis
    image: valkey/valkey:7.2
    command: "--requirepass '${REDIS_PASSWORD}'"
    environment:
      - "REDIS_PORT=${REDIS_PORT:-6379}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
    networks:
      - misp-network
    volumes:
      - ./vol/redis:/data

  db:
    container_name: misp-db
    image: mariadb:10.11
    restart: always
    environment:
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    command: "\
      --innodb-buffer-pool-size=${INNODB_BUFFER_POOL_SIZE:-2048M} \
      --innodb-change-buffering=${INNODB_CHANGE_BUFFERING:-none} \
      --innodb-io-capacity=${INNODB_IO_CAPACITY:-1000} \
      --innodb-io-capacity-max=${INNODB_IO_CAPACITY_MAX:-2000} \
      --innodb-log-file-size=${INNODB_LOG_FILE_SIZE:-600M} \
      --innodb-read-io-threads=${INNODB_READ_IO_THREADS:-16} \
      --innodb-stats-persistent=${INNODB_STATS_PERSISTENT:-ON} \
      --innodb-write-io-threads=${INNODB_WRITE_IO_THREADS:-4}"
    networks:
      - misp-network
    volumes:
      - ./vol/mysql:/var/lib/mysql

  misp-core:
    container_name: misp-core
    image: ghcr.io/misp/misp-docker/misp-core:${CORE_RUNNING_TAG:-latest}
    build:
      context: core/.
      args:
        - CORE_TAG=${CORE_TAG}
        - PHP_VER=${PHP_VER}
    depends_on:
      - redis
      - db
      - misp-modules
    ports:
      - "980:80"
      - "443:443"
    networks:
      - misp-network
    volumes:
      - ./vol/configs:/var/www/MISP/app/Config/
      - ./vol/logs:/var/www/MISP/app/tmp/logs/
      - ./vol/files:/var/www/MISP/app/files/
      - ./vol/ssl:/etc/nginx/certs/
      - ./vol/gnupg:/var/www/MISP/.gnupg/
    environment:
      - "BASE_URL=${BASE_URL}"
      - "MYSQL_HOST=misp-db"
      - "MYSQL_PORT=${MYSQL_PORT:-3306}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "REDIS_HOST=misp-redis"
      - "REDIS_PORT=${REDIS_PORT:-6379}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
      - "ADMIN_EMAIL=${ADMIN_EMAIL}"
      - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
      - "ADMIN_ORG=${ADMIN_ORG}"
      - "ADMIN_ORG_UUID=${ADMIN_ORG_UUID}"
      - "CRON_USER_ID=${CRON_USER_ID}"
      - "DISABLE_IPV6=${DISABLE_IPV6}"
      - "DISABLE_SSL_REDIRECT=${DISABLE_SSL_REDIRECT}"
      - "PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-2048M}"
      - "PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-300}"
      - "PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-50M}"
      - "PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-50M}"
      - "PHP_SESSION_COOKIE_SECURE=${PHP_SESSION_COOKIE_SECURE:-true}"
      - "PHP_SESSION_COOKIE_SAMESITE=${PHP_SESSION_COOKIE_SAMESITE:-Lax}"
      - "OIDC_ENABLE=${OIDC_ENABLE}"
      - "LDAP_ENABLE=${LDAP_ENABLE}"

  misp-modules:
    container_name: misp-modules
    image: ghcr.io/misp/misp-docker/misp-modules:${MODULES_RUNNING_TAG:-latest}
    build:
      context: modules/.
      args:
        - MODULES_TAG=${MODULES_TAG}
    depends_on:
      - redis
    networks:
      - misp-network
    volumes:
      - ./vol/misp-modules:/data
    environment:
      - "REDIS_BACKEND=misp-redis"
      - "REDIS_PORT=${REDIS_PORT:-6379}"
      - "REDIS_PW=${REDIS_PASSWORD}"

networks:
  misp-network:
    external: true
